### ISSUE TITLE
拉下来的代码无法跑

### ISSUE THREAD

**Issue by chengzhenguo1** [landluck/react-ant-admin#14]
![image](https://user-images.githubusercontent.com/51019050/113420262-99b85180-93fb-11eb-9290-759f0004d93f.png)

**Comment by chenchifeng** [comment]
**用`npm install`去安装就可以了.**

这个你应该是用了yarn来安装吧,我今天也是遇到同样的问题了,然后后面发现是typescript版本的问题.
这里的typescript版本比较低,然后用yarn安装的时候没有lock版本信息,然后有些依赖安装了新版的,而typescript是旧版的,所以就报错跑不起来了.
我试过把typescript的版本给升了,但是发现这里面有些依赖又是旧版的,然后又报了其他的错.
最后直接用`npm install`去安装,里面有npm的依赖版本锁文件,然后安装的就是正确版本的依赖,然后就跑起来了.

**Comment by yxf14789632** [comment]
npm install @ant-design/icons@4.0.0  就可以解决了，不用改别的

**Comment by chengzhenguo1** [comment]
> npm 安装@ant设计/icons@4.0.0 件，分期分批分批

感谢，已经能跑了
